INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad de Sevilla");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad de Granada");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad de Córdoba");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad de Málaga");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad de Cádiz");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad de Almería");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad de Huelva");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad de Jaén");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Internacional de Andalucía");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Pablo de Olavide");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Loyola Andalucía");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad de Zaragoza");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad San Jorge");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad de Oviedo");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad de las Islas Baleares");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad de La Laguna");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad de Las Palmas de Gran Canaria");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Europea de Canarias");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Fernando Pessoa-Canarias");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad de Cantabria");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Europea del Atlántico");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad de Castilla-La Mancha");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad de Salamanca");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad de Valladolid");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Pontificia de Salamanca");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad de León");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad de Burgos");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Católica Santa Teresa de Jesús de Ávila");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Europea Miguel de Cervantes");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad IE");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Internacional Isabel I de Castilla");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad de Barcelona");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Autónoma de Barcelona");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Politécnica de Cataluña");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Pompeu Fabra");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Ramon Llull");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad de Gerona");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad de Lérida");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Rovira i Virgili");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Abierta de Cataluña");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Internacional de Cataluña");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad de Vich");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Abad Oliva CEU");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad de Valencia");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Politécnica de Valencia");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad de Alicante");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Jaime I");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Miguel Hernández de Elche");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad CEU Cardenal Herrera");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Católica de Valencia San Vicente Mártir");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Internacional de Valencia");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Europea de Valencia");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad de Extremadura");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad de Santiago de Compostela");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad de La Coruña");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad de Vigo");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad de La Rioja");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Internacional de La Rioja");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Complutense de Madrid");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Pontificia Comillas");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Internacional Menéndez Pelayo");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Autónoma de Madrid");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Politécnica de Madrid");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Nacional de Educación a Distancia");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad de Alcalá");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Carlos III de Madrid");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Alfonso X el Sabio");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad CEU San Pablo");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Francisco de Vitoria");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Antonio de Nebrija");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Europea de Madrid");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Rey Juan Carlos");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Camilo José Cela");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad a Distancia de Madrid");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Eclesiástica San Dámaso");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad de Murcia");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Católica San Antonio");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Politécnica de Cartagena");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad de Navarra");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad Pública de Navarra");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad de Deusto");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad del País Vasco");
INSERT INTO `aps`.`universidades`(`nombre`) VALUES ("Universidad de Mondragón");